global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    akash:
        type: cosmos
        value:
            key: default
            chain-id: akashnet-2
            rpc-addr: https://akash-rpc.polkachu.com:443
            account-prefix: akash
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uakt
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    assetmantle:
        type: cosmos
        value:
            key: default
            chain-id: mantle-1
            rpc-addr: https://rpc.asset-mantle.ezstaking.io:443
            account-prefix: mantle
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01umntl
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    axelar:
        type: cosmos
        value:
            key: default
            chain-id: axelar-dojo-1
            rpc-addr: https://rpc-axelar-ia.notional.ventures:443/
            account-prefix: axelar
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uaxl
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    bandchain:
        type: cosmos
        value:
            key: default
            chain-id: laozi-mainnet
            rpc-addr: http://rpc.laozi1.bandchain.org:80
            account-prefix: band
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uband
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    bitcanna:
        type: cosmos
        value:
            key: default
            chain-id: bitcanna-1
            rpc-addr: https://bitcanna-rpc.polkachu.com:443
            account-prefix: bcna
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ubcna
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    bitsong:
        type: cosmos
        value:
            key: default
            chain-id: bitsong-2b
            rpc-addr: https://rpc-bitsong.itastakers.com:443
            account-prefix: bitsong
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ubtsg
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    chihuahua:
        type: cosmos
        value:
            key: default
            chain-id: chihuahua-1
            rpc-addr: https://rpc-chihuahua.ecostake.com:443
            account-prefix: chihuahua
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.1uhuahua
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    comdex:
        type: cosmos
        value:
            key: default
            chain-id: comdex-1
            rpc-addr: https://rpc-comdex.zenchainlabs.io:443/
            account-prefix: comdex
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ucmdx
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    cosmoshub:
        type: cosmos
        value:
            key: default
            chain-id: cosmoshub-4
            rpc-addr: https://rpc-cosmoshub.ecostake.com:443
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uatom
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    crescent:
        type: cosmos
        value:
            key: default
            chain-id: crescent-1
            rpc-addr: https://rpc.crescent.pupmos.network:443
            account-prefix: cre
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ucre
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    evmos:
        type: cosmos
        value:
            key: default
            chain-id: evmos_9001-2
            rpc-addr: https://rpc-evmos-ia.notional.ventures:443
            account-prefix: evmos
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.25aevmos
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    juno:
        type: cosmos
        value:
            key: default
            chain-id: juno-1
            rpc-addr: https://rpc-juno.itastakers.com:443
            account-prefix: juno
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ujuno
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    kichain:
        type: cosmos
        value:
            key: default
            chain-id: kichain-2
            rpc-addr: https://rpc.kichain.ezstaking.io:443
            account-prefix: ki
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uxki
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    kujira:
        type: cosmos
        value:
            key: default
            chain-id: kaiyo-1
            rpc-addr: https://rpc.kaiyo.kujira.setten.io:443
            account-prefix: kujira
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ukuji
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    likecoin:
        type: cosmos
        value:
            key: default
            chain-id: likecoin-mainnet-2
            rpc-addr: https://mainnet-node.like.co:443/rpc/
            account-prefix: like
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01nanolike
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    omniflixhub:
        type: cosmos
        value:
            key: default
            chain-id: omniflixhub-1
            rpc-addr: https://omniflixhub-rpc.skynetvalidators.com:443
            account-prefix: omniflix
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uflix
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    osmosis:
        type: cosmos
        value:
            key: default
            chain-id: osmosis-1
            rpc-addr: https://rpc-osmosis-ia.notional.ventures:443/
            account-prefix: osmo
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uosmo
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    persistence:
        type: cosmos
        value:
            key: default
            chain-id: core-1
            rpc-addr: https://rpc.core.persistence.one:443
            account-prefix: persistence
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uxprt
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    regen:
        type: cosmos
        value:
            key: default
            chain-id: regen-1
            rpc-addr: http://public-rpc.regen.vitwit.com:26657
            account-prefix: regen
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uregen
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    rizon:
        type: cosmos
        value:
            key: default
            chain-id: titan-1
            rpc-addr: https://rpcapi.rizon.world:443/
            account-prefix: rizon
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uatolo
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    secretnetwork:
        type: cosmos
        value:
            key: default
            chain-id: secret-4
            rpc-addr: https://rpc.secret.forbole.com:443/
            account-prefix: secret
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uscrt
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    sentinel:
        type: cosmos
        value:
            key: default
            chain-id: sentinelhub-2
            rpc-addr: https://rpc-sentinel-ia.notional.ventures:443/
            account-prefix: sent
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01udvpn
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    sifchain:
        type: cosmos
        value:
            key: default
            chain-id: sifchain-1
            rpc-addr: https://rpc.sifchain.finance:443
            account-prefix: sif
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01rowan
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    sommelier:
        type: cosmos
        value:
            key: default
            chain-id: sommelier-3
            rpc-addr: https://sommelier-rpc.polkachu.com:443
            account-prefix: somm
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01usomm
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    stargaze:
        type: cosmos
        value:
            key: default
            chain-id: stargaze-1
            rpc-addr: https://rpc.stargaze.pupmos.network:443/
            account-prefix: stars
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ustars
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    umee:
        type: cosmos
        value:
            key: default
            chain-id: umee-1
            rpc-addr: https://rpc-umee-ia.notional.ventures:443/
            account-prefix: umee
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uumee
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
paths:
    akash-juno:
        src:
            chain-id: akashnet-2
            client-id: 07-tendermint-84
            connection-id: connection-58
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-80
            connection-id: connection-47
        src-channel-filter:
            rule: ""
            channel-list: []
    assetmantle-juno:
        src:
            chain-id: mantle-1
            client-id: 07-tendermint-22
            connection-id: connection-4
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-167
            connection-id: connection-113
        src-channel-filter:
            rule: ""
            channel-list: []
    axelar-juno:
        src:
            chain-id: axelar-dojo-1
            client-id: 07-tendermint-25
            connection-id: connection-14
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-150
            connection-id: connection-97
        src-channel-filter:
            rule: ""
            channel-list: []
    bitcanna-juno:
        src:
            chain-id: bitcanna-1
            client-id: 07-tendermint-12
            connection-id: connection-11
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-110
            connection-id: connection-70
        src-channel-filter:
            rule: ""
            channel-list: []
    bitsong-juno:
        src:
            chain-id: bitsong-2b
            client-id: 07-tendermint-9
            connection-id: connection-9
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-33
            connection-id: connection-26
        src-channel-filter:
            rule: ""
            channel-list: []
    chihuahua-juno:
        src:
            chain-id: chihuahua-1
            client-id: 07-tendermint-54
            connection-id: connection-30
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-79
            connection-id: connection-46
        src-channel-filter:
            rule: ""
            channel-list: []
    comdex-juno:
        src:
            chain-id: comdex-1
            client-id: 07-tendermint-30
            connection-id: connection-19
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-92
            connection-id: connection-55
        src-channel-filter:
            rule: ""
            channel-list: []
    cosmoshub-juno:
        src:
            chain-id: cosmoshub-4
            client-id: 07-tendermint-439
            connection-id: connection-372
        dst:
            chain-id: juno-1
            client-id: 07-tendermint-3
            connection-id: connection-2
        src-channel-filter:
            rule: ""
            channel-list: []
    crescent-juno:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-160
            connection-id: connection-107
        dst:
            chain-id: crescent-1
            client-id: 07-tendermint-5
            connection-id: connection-3
        src-channel-filter:
            rule: ""
            channel-list: []
    evmos-juno:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-148
            connection-id: connection-96
        dst:
            chain-id: evmos_9001-2
            client-id: 07-tendermint-14
            connection-id: connection-8
        src-channel-filter:
            rule: ""
            channel-list: []
    juno-osmosis:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: osmosis-1
            client-id: 07-tendermint-1457
            connection-id: connection-1142
        src-channel-filter:
            rule: ""
            channel-list: []
    juno-persistence:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-89
            connection-id: connection-51
        dst:
            chain-id: core-1
            client-id: 07-tendermint-49
            connection-id: connection-48
        src-channel-filter:
            rule: ""
            channel-list: []
    juno-secretnetwork:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-108
            connection-id: connection-68
        dst:
            chain-id: secret-4
            client-id: 07-tendermint-23
            connection-id: connection-9
        src-channel-filter:
            rule: ""
            channel-list: []
    juno-sifchain:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-9
            connection-id: connection-8
        dst:
            chain-id: sifchain-1
            client-id: 07-tendermint-37
            connection-id: connection-17
        src-channel-filter:
            rule: ""
            channel-list: []
    juno-stargaze:
        src:
            chain-id: juno-1
            client-id: 07-tendermint-44
            connection-id: connection-30
        dst:
            chain-id: stargaze-1
            client-id: 07-tendermint-13
            connection-id: connection-11
        src-channel-filter:
            rule: ""
            channel-list: []
